name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'Standoff 2 User ID'
        required: true
        default: 'default'
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install firefox --with-deps
    - name: Run tests
      run: |
        export USER_ID=${{ github.event.inputs.user_id }} 
        pytest -s
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: user_data_${{ github.event.inputs.user_id }}
        path: result.json